### ISSUE TITLE
Sodium Contained in MekaSuit Should Not Decrease when Having Fire Resistance

### ISSUE THREAD

**Issue by RobuxShooters** [MorningSage/Mekanism_Addons#13]
Currently, if you have Fire Resistance while also having Sodium in the MekaSuit, the Sodium will still get turned into Superheated Sodium. I would suggest for this to not occur when the player has Fire Resistance and have the Sodium remain until Fire Resistance wears off.

**Comment by MorningSage** [comment]
Another great suggestion.  I’ll make this change, too, thank you.

Without sounding like a broken record and in case people haven’t seen other issues, I’m on holiday through the rest of the year without my computer. As soon as I’m back, I’ll make this change.

Keep these coming!

**Comment by MorningSage** [comment]
Fixed in Dev
