### ISSUE TITLE
Meka-Tool AOE breaking Bedrock

### ISSUE THREAD

**Issue by noeneto** [MorningSage/Mekanism_Addons#6]
When in the area of the AOE, the Meka-Tool breaks any block, even the bedrock itself.

Screenshot for example;
https://imgur.com/a/nKD4GbF

**Comment by MorningSage** [comment]
Hahaha... This is one of those facepalm moments...

I'll fix it, thanks!

**Comment by MorningSage** [comment]
Fixed.  Posting to CurseForge now.
